apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: a2a-registry

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - opensearch-deployment.yaml
  - registry-deployment.yaml
  - runner-deployment.yaml
  - ui-deployment.yaml
  - ingress.yaml

commonLabels:
  app: a2a-registry
  managed-by: kustomize

